name: catalog-services
services:
  database:
    container_name: 'postgres-catalog-service'
    image: 'postgres:16.0-alpine3.18'
    env_file:
      - ../../.env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '54323:5432'
volumes:
  postgres:
